# Site settings
title: Eukarya Farm
email: tom@eukaryafarm.com
description: Gourmet Mushroom Farm located in Fort Lupton, Colorado
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Kohl Kinning
# street_address:
city: Ft. Lupton
state: CO
zip_code: 80621
country: United States of America


icon: fa-toadstool

# Social settings
#facebook_url:
#github_url: 
instagram_url: https://www.instagram.com/kingdomcomefarm_co/
#linkedin_url: 
#pinterest_url:
#slack_url:
#twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown

sass:
style: compressed
